#!/usr/bin/env bash

set -euo pipefail

# This script runs the self tests for the bash-lib repo.

# This script is an entry point, so init
# is not assumed to have been run
# shellcheck disable=SC2086,SC2046
. $(dirname ${BASH_SOURCE[0]})/../init
set +eu


# Check vital tools are installed
if ! command -v summon >/dev/null; then
    bl_die "Summon must be installed and configured in order to run tests"
fi

if ! command -v docker >/dev/null; then
    bl_die "Docker must be installed and configured in order to run tests"
fi

# could be tap, junit or pretty
readonly BATS_OUTPUT_FORMAT="${BATS_OUTPUT_FORMAT:-pretty}"
readonly BATS_SUITE="${BATS_SUITE:-BATS}"
readonly TAP_FILE="${BASH_LIB_DIR}/bats.tap"

# return code
rc=0

if [[ ${#} -eq 0 ]]; then
    echo "No test scripts specified, running all."
    scripts="${BASH_LIB_DIR}/tests-for-this-repo/*.bats"
else
    scripts="${*}"
fi

readonly summon_cmd="summon -f ${BASH_LIB_DIR}/secrets.yml"

case $BATS_OUTPUT_FORMAT in
    pretty)
        # shellcheck disable=SC2086
        if ! ${summon_cmd} ${BATS_CMD} ${scripts}; then
            rc=1
        fi
    ;;
    tap | junit)
        # shellcheck disable=SC2086
        if ! ${summon_cmd} ${BATS_CMD} ${scripts} > ${TAP_FILE}; then
            rc=1
        fi
        echo "TAP Output written to ${TAP_FILE}"
    ;;
    *)
        echo "Invalid BATS_OUTPUT_FORMAT: ${BATS_OUTPUT_FORMAT}, valid options: pretty, junit, tap."
        exit 1
    ;;
esac

#Convert TAP to Junit when required
if [[ "${BATS_OUTPUT_FORMAT}" == junit ]]; then
    # Run tap2junit docker image to convert BATS TAP output to Junit for consumption by jenkins
    readonly  JUNIT_FILE="${BASH_LIB_DIR}/${BATS_SUITE}-junit.xml"
    bl_tap2junit < "${TAP_FILE}" > "${JUNIT_FILE}"
    echo "Junit output written to ${JUNIT_FILE}"
fi

exit ${rc}
