#!/bin/bash

set -euo pipefail

function main() {
  echo Starting platform login

  gcloud auth activate-service-account \
    --key-file "${GCLOUD_SERVICE_KEY}"

  gcloud container clusters get-credentials \
    "${GCLOUD_CLUSTER_NAME}" \
    --zone "${GCLOUD_ZONE}" \
    --project "${GCLOUD_PROJECT_NAME}"

  docker login "${DOCKER_REGISTRY_URL}" \
    -u oauth2accesstoken \
    -p "$(gcloud auth print-access-token)"

  echo Platform Login Complete
}

main
