#!/bin/bash

: "${BASH_LIB_DIR:?BASH_LIB_DIR must be set. Please source bash-lib/init before other scripts from bash-lib.}"

#https://stackoverflow.com/a/23002317
function bl_abs_path() {
    # generate absolute path from relative path
    # path     : relative filename
    # return : absolute path
    if [[ -z "${1:-}" ]]; then
        path="."
    else
        path="${1}"
    fi
    if [ -d "${path}" ]; then
        # dir
        (bl_spushd "${path}"; pwd)
    elif [ -f "${path}" ]; then
        # file
        if [[ ${path} = /* ]]; then
            echo "${path}"
        elif [[ ${path} == */* ]]; then
            echo "$(bl_spushd "${path%/*}"; pwd)/${path##*/}"
        else
            echo "$(pwd)/${path}"
        fi
    fi
}
